/*
	Author : Houssam BACAR
	Project Name : Mirtille Virtual Machine
	Description : Wrapping C Exit/Errors Codes
	Date : 04/12/2025
*/

#ifndef __ME_ERROR_MIRTILLE_MACHINE_ERROR_CODE__H__
#define __ME_ERROR_MIRTILLE_MACHINE_ERROR_CODE__H__


typedef enum {
	ME_EXIT_FAILURE					= -1, 
	ME_EXIT_SUCCESS					= 0, 
	ME_EXIT_ABNORMAL_TERMINATION	= 1,
	ME_EXIT_ERROR_OCCURS			= 2, 
	ME_EXIT_COMMAND_NOT_FOUND		= 127, 
	ME_EXIT_PROGRAM_ABORTED_SIGILL	= 132, 
	ME_EXIT_PROGRAM_ABORTED_SIGTRAP = 133, 
	ME_EXIT_PROGRAM_ABORTED_SIGABRT = 134, 
	ME_EXIT_PROGRAM_ABORTED_SIGFPE	= 136, 
	ME_EXIT_PROGRAM_MEMORY			= 137, 
	ME_EXIT_PROGRAM_ABORTED_SIGBUS	= 138, 
	ME_EXIT_SEGMENTATION_FAULT		= 139,
	ME_EXIT_PROGRAM_ABORTED_SIGXCPU = 152, 
	ME_EXIT_PROGRAM_ABORTED_SIGXFSZ = 153, 
	ME_EXIT_ABORTED_CPU 			= 158, 
	ME_EXIT_PROGRAM_ABORTED 	 	= 159
} MIRTILLE_MACHINE_ERROR_CODE;

const char * me_getStringErrorCode(MIRTILLE_MACHINE_ERROR_CODE code_mmec){
	switch(code_mmec){
		case ME_EXIT_FAILURE :
			return "ME_EXIT_FAILURE";

		case ME_EXIT_SUCCESS:
			return "ME_EXIT_SUCCESS";
		case ME_EXIT_ABNORMAL_TERMINATION:
			return "ME_EXIT_ABNORMAL_TERMINATION";

		case ME_EXIT_ERROR_OCCURS:
			return "ME_EXIT_ERROR_OCCURS";

		case ME_EXIT_COMMAND_NOT_FOUND:
			return "ME_EXIT_COMMAND_NOT_FOUND";

		case ME_EXIT_PROGRAM_ABORTED_SIGILL:
			return "ME_EXIT_PROGRAM_ABORTED_SIGILL";

		case ME_EXIT_PROGRAM_ABORTED_SIGTRAP: 
			return "ME_EXIT_PROGRAM_ABORTED_SIGTRAP";

		case ME_EXIT_PROGRAM_ABORTED_SIGABRT:
			return "ME_EXIT_PROGRAM_ABORTED_SIGABRT"; 

		case ME_EXIT_PROGRAM_ABORTED_SIGFPE: 
			return "ME_EXIT_PROGRAM_ABORTED_SIGFPE";

		case ME_EXIT_PROGRAM_MEMORY:
			return "ME_EXIT_PROGRAM_MEMORY";

		case ME_EXIT_PROGRAM_ABORTED_SIGBUS:
			return "ME_EXIT_PROGRAM_ABORTED_SIGBUS";

		case ME_EXIT_SEGMENTATION_FAULT:
			return "ME_EXIT_SEGMENTATION_FAULT";

		case ME_EXIT_PROGRAM_ABORTED_SIGXCPU:
			return "ME_EXIT_PROGRAM_ABORTED_SIGXCPU";

		case ME_EXIT_PROGRAM_ABORTED_SIGXFSZ:
			return "ME_EXIT_PROGRAM_ABORTED_SIGXFSZ";

		case ME_EXIT_ABORTED_CPU:
			return "ME_EXIT_ABORTED_CPU";

		case ME_EXIT_PROGRAM_ABORTED:
			return "ME_EXIT_PROGRAM_ABORTED";

		default:
			return "ME_UNKNOWN_EXIT_CODE";
	}
}

#endif